name: howdycase
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  json_annotation: '>= 4.5.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  dartz:
  build_runner:
  freezed:
  json_serializable:
  freezed_annotation: